image: node:10.15.3

pipelines:
  default:
    - step:
        caches:
          - node-modules
          - yarn
        script:
          - yarn
          - yarn run format
          - git add -A
          - git diff-index --quiet HEAD || git commit -m"🎨 Auto-fix code
            formatting [skip ci]"
          - git push
definitions:
  caches:
    node-modules: ./node_modules
    yarn: /usr/local/share/.cache/yarn
